// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCstxy-JeLWdjP8_mhU9lYKdAJ8NwanuYo',
    appId: '1:105661377937:web:77b059f12ef92404033e30',
    messagingSenderId: '105661377937',
    projectId: 'greenhouse2-bc0e9',
    authDomain: 'greenhouse2-bc0e9.firebaseapp.com',
    databaseURL: 'https://greenhouse2-bc0e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse2-bc0e9.firebasestorage.app',
    measurementId: 'G-ZF3MWQW871',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOoVJt-gg-6PZibmHBlhw_o4HfzbUSZpI',
    appId: '1:105661377937:android:d3e5ce0af9da1c41033e30',
    messagingSenderId: '105661377937',
    projectId: 'greenhouse2-bc0e9',
    databaseURL: 'https://greenhouse2-bc0e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse2-bc0e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Z4S7LqAKDf2qu5v1vbNyBUlP-ReDF9I',
    appId: '1:105661377937:ios:aadc9e687a527ad0033e30',
    messagingSenderId: '105661377937',
    projectId: 'greenhouse2-bc0e9',
    databaseURL: 'https://greenhouse2-bc0e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse2-bc0e9.firebasestorage.app',
    iosBundleId: 'com.example.greenhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Z4S7LqAKDf2qu5v1vbNyBUlP-ReDF9I',
    appId: '1:105661377937:ios:aadc9e687a527ad0033e30',
    messagingSenderId: '105661377937',
    projectId: 'greenhouse2-bc0e9',
    databaseURL: 'https://greenhouse2-bc0e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse2-bc0e9.firebasestorage.app',
    iosBundleId: 'com.example.greenhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCstxy-JeLWdjP8_mhU9lYKdAJ8NwanuYo',
    appId: '1:105661377937:web:f98e77137f98563d033e30',
    messagingSenderId: '105661377937',
    projectId: 'greenhouse2-bc0e9',
    authDomain: 'greenhouse2-bc0e9.firebaseapp.com',
    databaseURL: 'https://greenhouse2-bc0e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse2-bc0e9.firebasestorage.app',
    measurementId: 'G-T4GS8PH5H5',
  );
}
